# Generated by Django 5.1.1 on 2024-10-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorValue', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app_api.coleccion')),
            ],
        ),
    ]
