# Generated by Django 5.1.1 on 2024-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sensorValue',
            field=models.FloatField(),
        ),
    ]
